knative-extensions/reconciler-test

pkg/test/context.go, pkg/test/context_test.go, pkg/test/environment/cluster.go, pkg/test/environment/images.go, pkg/test/environment/ingress.go, pkg/test/environment/spoof.go, pkg/test/feature/states.go, pkg/test/feature/states_test.go, pkg/test/requirement/level.go, pkg/test/requirement/level_test.go
[Previously in #8](https://github.com/knative-sandbox/reconciler-test/pull/8/files#) I had `test.T`  separate from the `Config` interface. In practice this meant you had to cast the config to access certain properties.
I merged the two in this PR and changed the required signature when invoking subtests.
The functions that should be passed to subtests (`Run`, `Alpha`, `Must` etc..) should be take the same context that invoked the test
```go
// in my _test.go file
func RunConformance(t *testing.T) {
ctx := MyTestContext{...}
test.Init(ctx, t)
ctx.Alpha("some alpha feature", TestAlphaFeature)
}
// somewhere else
func TestAlphaFeature(ctx *MyTestContext) {
ctx.Must("do something", func(subctx *MyTestContext) {
subctx.Fatal("failed to do something")
})
}
```
I also realize eventing didn't use …
=> conformance lib poc

pkg/test/context.go, pkg/test/context_test.go
Defaulting to `All` in AddFlags didn't allow for a user to enable a specific level or state because internally we were ORing with a bitset
=> Change how we default feature states & requirement levels

pkg/test/context.go
A lot of networking tests seem to use `context.Background()`.  Secondly this is a jumping off point for the context to be decorated in `Setup`
=> Include a default parent context

pkg/environment/images.go, pkg/environment/interfaces.go, pkg/environment/magic.go, pkg/k8s/wait.go, pkg/manifest/installer.go, pkg/manifest/templates.go, test/example/config/echo/echo.go, test/example/config/echo/echo.yaml, test/example/config/producer/producer.go, test/example/config/producer/producer.yaml, test/example/config/recorder/recorder.go, test/example/config/recorder/recorder.yaml
tl;dr: `image: { .images.magicName }` --> `image: ko://some/go/package`
Fixes: https://github.com/knative-sandbox/reconciler-test/issues/34
This change takes some opinions out of the testing framework, we will use `ko://` to signal we want to make a container. 
This is overwritten if you use something like the following:
```
// The following could be used to bypass the image generation process.
import "knative.dev/reconciler-test/pkg/environment"
func init() {
environment.WithImages(map[string]string{
"ko://knative.dev/reconciler-test/images/recorder": "example.azurecr.io/kn/recorder@sha256:1938a18961f21262278dc03d18be190c630bef95a9ca0c62ca08af2528dbfd86",
"ko://knative.dev/reconciler-test/test/example/cmd/echo": "example.azurecr.io/kn/echo@sha256:0933ea6bf2799b08653c0e729d63372629b42c6933 …
```
=> Use ko:// to signal that we would like the test framework to produce images.

pkg/k8s/steps.go
- Adding IsReady for downstream usage.
Fixes #53 
```release-note
k8s.IsReady() is now usable.
```
=> adding IsReady for downstream usage

pkg/k8s/steps.go
- :bug: The original IsAddressable code came from Brokers, Brokers do not have address pointers or I never ran into a case where it was nil. Was getting NPE when integrating the method. This fixes those issues.
/kind bug
Fixes #
```release-note
Fix NPE on k8s.IsAddressable().
```
=> KResource has address as a pointer, test it for nil

pkg/environment/magic.go, pkg/feature/collapse.go, test/e2e/environment_test.go, test/e2e/main_test.go
- :broom: Now `Setup`, `Teardown` and `Requirement` run ordered and sequentially, while `Assert` is tagged to run in parallel. This makes the setup, teardown and requirement phases of the test predictable
- :gift: Test for the runtime constraints of the tests
=> Running constraints of different timings

pkg/eventshub/options.go, pkg/k8s/steps.go
- `k8s.Address()` returns the url of an addressable.
- `k8s.IsAddress()` uses `k8s.Address()`
- New entry for eventshub: `StartSenderURL`, to pass the sink directly as a url.
```release-note
Adding `k8s.Address()`, it returns the url of an addressable.
Adding `eventshub.StartSenderURL()`, to pass the sink directly as a url.
```
=> Add utility to return the address of an Addressable.

pkg/eventshub/assert/doc.go, pkg/eventshub/assert/event_info_matchers.go, pkg/eventshub/assert/step.go, pkg/eventshub/event_info_store.go, pkg/eventshub/options.go, test/example/recorder_feature.go
- :gift: Moved all the asserts under a specific package to simplify the assertions usage
- :gift: Added a matcher for status code
- :gift: Added an eventshub option to send directly to an addressable matcher for status code
=> Improve eventshub assertions UX

pkg/images/ko.go
This is to make the reconciler test configurable for different platforms. This change is in line with https://github.com/knative/eventing/pull/4763.
- Add an argument `--platform` if the env variable `PLATFORM` is set, otherwise the argument is empty.
=> Allow to specify platform for reconciler test

pkg/environment/magic.go
This should fix https://github.com/knative/eventing/issues/4637
=> Context cancelling should be tied to the single test execution

README.md, pkg/environment/interfaces.go, pkg/environment/magic.go, pkg/feature/feature.go, test/e2e/environment_test.go, test/example/config/echo/echo.go, test/example/config/echo/echo.yaml, test/example/config/echo/echo_test.go, test/example/echo_feature.go, test/example/examples_test.go
fixes https://github.com/knative-sandbox/reconciler-test/issues/65
- :gift: Adding FeatureSet, a wrapper around a set of features.
- :gift: Adding TestSet, a test entry point to run a FeatureSet.
We need a way to vendor a group of features rather than individuals, the aim here is to provide a set of features that might be required for something like a conformance test, and it does not make much sense to vendor them individually as a burden to the downstream user of these.
```release-note
Adding feature.FeatureSet and Environment.TestSet.
```
=> Adding FeatureSet and TestSet

pkg/feature/feature.go
Because when developing e2e/integration tests the user doesn't care about the compliance levels, this PR adds a `feature.Assert` which defaults to the highest level and state 
- :gift: Add `feature.Assert` for e2e tests developers
=> Added feature.Assert shortcut

pkg/environment/execution.go, pkg/environment/magic.go, pkg/environment/namespace.go, pkg/environment/t.go, pkg/feature/t.go, test/e2e/environment_fails_test.go, test/e2e/environment_test.go
- :gift: Now all asserts are executed, no matter their level, but the ones not required by the input flags (https://github.com/knative-sandbox/reconciler-test/pull/119/files#diff-36dc7755231472dee1b65e70532635dce8e7d0edcfec67c9db7b1d8c0307998dR258) won't fail the test. Thanks to this, we can do true conformance testing, running all the tests but passing the suite only if a certain level is reached (in #118 I discuss how we could implement the reporting for that)
- :gift: Introduce `Deadline` and `Cleanup` in `feature.T`
- :broom: Renamed `requirementT` to `skippingT` to highlight its behaviour
- :bug: Fix again the context issue, which was mistakenly reintroduce in #112
- :broom: Some names cleanup and things moved
- :bug: Fix …
=> More refactoring for the execution

README.md, pkg/environment/magic.go, test/e2e/environment_fails_test.go, test/e2e/environment_test.go, test/example/examples_test.go
fixes https://github.com/knative-sandbox/reconciler-test/issues/40
We provide a hook to allow a user to opt into a managed environment, they are free to not use this option and call `env.Finish()` directly. 
This is a non-API breaking change.
=> auto manage lifecycle of env

pkg/environment/magic.go, pkg/environment/namespace.go, pkg/environment/t.go, pkg/environment/timings.go, pkg/k8s/job.go, pkg/k8s/steps.go, pkg/k8s/wait.go, test/example/echo_feature.go, test/example/examples_test.go
This also adds timing defaults to/from context and a way to set that on env creation.
No API breaking changes.
=> adding helper to wait for an address for a resource.

pkg/environment/magic.go
This allows the existing test infra to collect the logs https://github.com/knative/eventing/issues/5076
Also prefixing with `test` is more reasonable and easy to understand
=> Use test as prefix for test namespaces

pkg/test_images/eventshub/event_info.go, pkg/test_images/eventshub/sender/sender.go
Add a field to EventInfo, Id. This is stuffed with the Event.Id so that we can actually correlate Sent / Response events
and inspect the statuscode to make sure it's what we expect.
Example usage here:
https://github.com/vaikas/eventing/commit/c9cd237e10f6e9f5f32b8a6f29a91c3247c61c99
=> add id for correlation

pkg/eventshub/options.go, pkg/test_images/eventshub/dropevents/receiver.go, pkg/test_images/eventshub/receiver/receiver.go, pkg/test_images/eventshub/sender/sender.go
Fix  #99
- Added an option to define the input method
- Added an option to drop events (already implemented previously, it was just missing the options)
=> [eventshub] Define the method to send http requests and drop events

pkg/eventshub/options.go, pkg/test_images/eventshub/sender/sender.go
- :gift: Add a new option to event sender to override the Time field of the event when sending
=> [eventshub] Override time when sending events

pkg/environment/execution.go, pkg/environment/magic.go, test/e2e/environment_fails_test.go
Fix #32 
- :gift: Now stepfn can panic. Handle panics and mark the test as failed without quitting the test process
- :broom: Added a test to check both panics and fatal
=> Now stepfn can panic safely

pkg/environment/execution.go, pkg/environment/magic.go, test/e2e/environment_test.go
This PR includes assorted fixes and small mistakes I've found in the attempt to fix the panic experienced here: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_eventing/5149/pull-knative-eventing-reconciler-tests/1375038550466105344
* The cleanup was registered on the wrong t in `execution.go`
* Some comments on the semantics of methods in execution.go
* Remove unnecessary nested test
* Fix subtest name
* Removed unnecessary internal context
=> Hunting the panic issue

pkg/eventshub/assert/step.go, pkg/eventshub/event_info_store.go, test/example/recorder_feature.go
I found that the tests panic with 
```
goroutine 49 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/snichols/go/src/github.com/knative-sandbox/reconciler-test/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x2479560, 0xc0002cfa70)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
testing.(*common).Fail(0xc000fa2780)
/usr/local/go/src/testing/testing.go:698 +0x125
testing.(*common).Errorf(0xc000fa2780, 0x2799367, 0x33, 0xc0002cf950, 0x1, 0x1)
/usr/local/go/src/testing/testing.go:804 +0x93
knative.dev/reconciler-test/pkg/eventshub.(*Store).Handle(0xc0003140c0, 0xc000f92000)
/Users/snichols/go/src/github.com/knative-sandbox/reconciler-test/pkg/eventshub/event_info_store.go:102 +0x3a3 …
```
=> do not use t outside of test

pkg/environment/magic.go, pkg/milestone/emitter.go, pkg/milestone/factory.go
This change enables consumers of the event milestone stream plan ahead for what results are going to come for a single feature run. This could be used to implement something like a progress bar, etc.
=> Implement step planning event

README.md, pkg/environment/magic.go, test/e2e/environment_fails_test.go, test/e2e/environment_test.go
fixes #181 
- **Requirement** is used to validate the cluster, environment, or anything
else. Think of this as a preflight validation for the assertions. This can be
used as a fast-fail for a feature test before running assert phase steps.
=> Fail on feature.Require errors.

README.md
=> fix tiny README typos

README.md, pkg/environment/flags.go, pkg/environment/magic.go, test/e2e/main_test.go
- :gift: Add --feature flag for filtering
- if not set, all features are run
- if set, the features are matched using the given regexp and the
feature is skipped if it doesn't match. Rather than use the built-in
skip, which skips the remainder of the test, none of the feature
phases are executed.
- eg. `go test -v -tags=e2e ./test/example/ --feature ^Noop$`
fixes #180
=> #180 add flag to allow filtering of features while running tests

.github/workflows/knative-downstream.yaml
`eventing-kafka` and `eventing-kafka-broker` are using rekt too!
=> Add Kafka projects to downstream tests

pkg/eventshub/prober.go
In trying to port [these e2e tests](https://github.com/knative/eventing/blob/main/test/e2e/channel_single_event_test.go) to rekt, I found myself needing to manually construct events and have eventshub deliver them via the [InputEventWithEncoding](https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/eventshub/options.go#L154) option. The problem I ran into then was that there is no way to register these events into the prober as expectations. As far as I can tell the only helper right now is `ExpectYAMLEvents`, which takes a file path.
=> Add a way to manually add event assertions

.github/workflows/kind-e2e.yaml, .github/workflows/knative-downstream.yaml, README.md, go.mod, pkg/eventshub/eventshub_test.go, pkg/eventshub/resources.go, pkg/manifest/installer.go, pkg/manifest/templates.go, resources/svc/service.go, resources/svc/service_test.go, test/example/config/echo/echo.go, test/example/config/echo/echo_test.go
- :gift:  YAML helpers now take an [fs.FS](https://golang.org/pkg/io/fs/#FS), allowing us to use the new [embed package](https://golang.org/pkg/embed/) for bundling yaml into test binaries
Fixes #193
=> Use go 1.16 embed for templates

pkg/feature/feature.go
Tests are currently named things like `events_have_passed_through_transform_service_events_have_passed_through_transform_service` because name is captured twice
=> Fix redundant name in Assert helper

pkg/eventshub/prober.go
Right now ReceiverDone and SenderDone don't fail, they erroneously call `Failed()` which just returns a bool.
=> Fail from ReceiverDone/SenderDone

pkg/eventshub/recorder_vent/recorder.go
With APIServerSources it's possible to get our own event back as a cloudevent, which causes a loop.
=> Skip emitting events if they are eventshub events

pkg/eventshub/prober.go, pkg/eventshub/resources.go
- :bug: Fix a race where we can miss events that are emitted before our event listener is registered
- :broom: Add more helpful logs with timestamps and resolved names
/kind bug
=> Fix eventshub race

.github/workflows/kind-e2e.yaml, cmd/eventshub/main.go, pkg/eventshub/103-pod.yaml, pkg/eventshub/event_info.go, pkg/eventshub/event_log.go, pkg/eventshub/eventshub.go, pkg/eventshub/eventshub_image.go, pkg/eventshub/eventshub_test.go, pkg/eventshub/resources.go, test/example/examples_test.go
While working on https://github.com/knative-sandbox/eventing-kafka-broker/issues/1077, I've found out we have some test images that are basically acting as receivers for events, in a similar fashion to eventshub. This refactor of the main of eventshub will allow to create our own kafk-esque eventshub image, which can receive messages both from http and from kafka.
This code doesn't change any behaviour, just moves a bit the code to avoid duplicating code in eventing-kafka-broker and in general allows people to create their own custom eventshub images. 
- :gift: Now most of the main code is moved to eventshub package, where downstream can use the `Start` method to assemble their own eventshub image
- :gift: Add a method to …
=> More flexible eventshub main

pkg/k8s/steps.go, pkg/k8s/wait.go
Add `IsNotReady` `StepFn` so that we can test the non-ready condition.
- Add IsNotReady StepFn
```release-note
Add IsNotReady StepFn
```
/cc @n3wscott @vaikas @lionelvillard
=> Add IsNotReady StepFn

pkg/eventshub/103-pod.yaml, pkg/eventshub/eventshub_test.go, pkg/eventshub/rbac/100-sa.yaml, pkg/eventshub/rbac/101-rbac.yaml, pkg/eventshub/rbac/rbac.go, pkg/eventshub/rbac/rbac_test.go, pkg/eventshub/rbac/resources.go, pkg/eventshub/resources.go
- Create ServiceAccount, Role, RoleBinding for eventshub with the same names as the namespace
- Extract the creation into a separate Install function so that we can later call this conditionally when running tests in pre-created namespace (this feature is TBD but I want to work on it soon) 
/kind cleanup
Fixes #191
```release-note
```
**Docs**
```docs
```
=> Use namespaced RBAC for eventshub

pkg/manifest/installer.go
This patch adds a workaround for knative/pkg#1509.
In the existing eventing testing library we have a similar workaround:
https://github.com/knative/eventing/blob/a8a30634681b2f0b23e5218348d9ae9a42cc00ff/test/lib/creation.go#L55-L72
- Retry on webhook EOF errors
/kind bug
Fixes https://github.com/knative/eventing/issues/5892
```release-note
Retry on webhook EOF errors.
```
**Docs**
```docs
None
```
=> Retry on webhook EOF errors

pkg/k8s/wait.go
This patch adds a condition to the isReady function so that isReady
returns true only when the observed generation is equal to the
object generation since after a resource update isReady might
return true even though the latest spec could lead to a resource
not being ready (due to misconfiguration or missing dependencies).
- isReady verifies resource generation and observed generation
/kind bug
Fixes #
```release-note
isReady verifies resource generation and observed generation.
```
**Docs**
```docs
None
```
=> isReady verifies resource generation and observed generation

pkg/eventshub/prober.go, pkg/k8s/steps.go
Using `log.Println` isn't good for debugging flaky tests.
In addition, logging only the number of events is helpful.
=> Use t.Log instead of log.Println for test scoped logging

pkg/k8s/wait.go
We were collecting logs but we weren't logging them.
=> Actually log pod logs on error waiting to become ready

.github/workflows/knative-downstream.yaml
Some projects require Go 1.17 to execute tests
/assign @lionelvillard @devguyio @dprotaso
=> Use Go 1.17 for downstream tests

pkg/feature/feature.go, pkg/feature/logging.go
This patch makes the method `f.DeleteResources` semantic more
clear by waiting for all resources to be deleted before returning.
This guarantees that once a feature passed to a next phase
resources were actually deleted.
=> Wait for resource deletions in DeleteResources

pkg/eventshub/103-pod.yaml, pkg/eventshub/eventshub_test.go, pkg/eventshub/resources.go
Senders don't start any server to receive readiness probes.
- Add EventHub readiness probe only in the receiver role
/kind bug
Fixes #301 
```release-note
Add EventHub readiness probe only in the receiver role
```
=> Add EventHub readiness probe only in the receiver role

pkg/environment/magic.go, pkg/feature/feature.go, test/example/echo_feature.go
- Features are stored by reference in a FeatureSet
- 🐛  fix issue with cleaning up resources where the original Feature is lost as it's passed by value. 
/kind bug
Fixes #299 
/assign @pierDipi  Since you worked on deleteResources recently :)
=> Features are stored by reference in a FeatureSet

pkg/manifest/templates.go
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
- :broom: Remove calling ExecuteLocalYAML func, b/c it is deprecated
/kind <kind>
Fixes #
```release-note
Removed ExecuteLocalYAML func, since it was deprecated.
```
**Docs**
```docs
```
=> Remove calling ExecuteLocalYAML func, b/c it is deprecated

.github/workflows/kind-e2e.yaml
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
Since we will probably be supporting Kubernetes v1.24 in the next release, and kind v0.13.0+ is required to run Kubernetes v1.24.0+ images, let's go ahead and bump the kind version now, so we have a chance to work out any issues before the next release.
Also bumping the ko version, since we were a few behind here.
=> Bump kind to v0.14 for e2e tests

pkg/eventshub/event_info_store.go
Debugging failed matches is complicated as it is without getting
all events that were collected.
=> Dump collected events on failed matches

pkg/eventshub/sender/sender.go
- 🐛  with the new ce checks on the broker conformance test suite sometimes… there are nil events here that are trying to get converted to string, this is a nil check to avoid the event source to error during the test runs
/kind bug
=> Fix String() call on nil events on event sender

pkg/eventshub/eventshub.go, pkg/eventshub/utils.go
This is a follow-up on https://github.com/knative/pkg/pull/2566.
- Get a reference to Tracer and call the Shutdown function on it when finishing work. This will flush buffered Spans to Zipkin.
```release-note
```
**Docs**
```docs
```
=> Properly shutdown tracer to flush Spans

README.md, pkg/environment/magic.go, pkg/environment/namespace.go
- Can be configured with an EnvOpt. By default will look for `default/kn-test-image-pull-secret`
```release-note
- Private registries can now be used for testing.
```
=> Copies an optional image pull secret to service account of new namespaces

pkg/environment/images.go, pkg/environment/images_test.go
If you uncomment the `copyRefs` code and just return the shared `is.refs` you will get:
`"Race detected during the execution of the test"` while executing the added test.
`go test -race -count=5 ./pkg/environment/...`
- copy image store map for read-only access
/kind bug
Fixes #410 
```release-note
Fix data race on publish images.
```
=> Fix data race on publish images

.github/workflows/knative-downstream.yaml
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
Updates the downstream test to use the `knative/actions` repo instead of the deprecated `knative-sandbox/actions-downstream-test` one
=> Use knative/actions downstream test

pkg/environment/execution.go, pkg/environment/magic.go, pkg/eventshub/prober.go, pkg/feature/feature.go, test/e2e/environment_fails_test.go, test/e2e/environment_test.go, test/example/prober_feature.go, test/example/recorder_feature.go
The `README` is explicity documenting that timings
(Setup, Requirement, etc) runs in order but steps with the
same timing runs in parallel while currently, this is not the
case and it is slowing test execution time down.
- Run steps with the same timing in parallel
```release-note
Run steps with the same timing in parallel as documented.
```
=> Run steps with the same timing in parallel as documented

pkg/eventshub/prober.go, pkg/eventshub/sender/sender.go, test/example/prober_feature.go
Multiple go routines can access the prober concurrently,
therefore we need to guard its field access with mutexes.
=> Fix prober concurrent access

pkg/eventshub/prober.go
`StartSenderToResource` expects that the resource is addressable but we don't verify it before calling `StartSenderToResource`.
=> Verify resource is addressable when sender is using GVR

pkg/k8s/wait.go
As per title, similar to 
https://github.com/knative-sandbox/reconciler-test/blob/a38bc32e26e4dddaa3259b51f6c5176304915321/pkg/k8s/wait.go#L134-L138
- Handle not found resources while waiting as in WaitForResourceCondition
=> Handle not found resources while waiting as in WaitForResourceCondition

pkg/eventshub/rbac/rbac.go
we might get already exists when multiple eventshub
are installed in parallel.
=> Handle already exists error in eventshub's RBAC install

pkg/k8s/wait.go
Endpoints are created asynchronously from the Service creation, so we need to keep polling when endpoints are not present.
=> Keep polling when endpoint is not present

pkg/eventshub/prober.go
When calling ReceiverInstall options parameter were appended to the the global prober receiver options which causes misconfiguration, evident when using the prober to install different receivers with different configurations.
=> Fix prober receiver install options

pkg/k8s/job.go, pkg/resources/job/job.go, pkg/resources/job/job.yaml, pkg/resources/job/job_test.go, pkg/resources/job/options.go
- :gift: Add helpers to create & interact with batchv1.Job resources
This PR is influenced by knative/eventing, and how they create resources in their tests (e.g. [test/rekt/resources/broker/broker.go](https://github.com/knative/eventing/blob/main/test/rekt/resources/broker/broker.go)). In future other helpers for k8s native resources could be added and the content from `reconciler-test/pkg/k8s/` could be migrated.
=> Add helpers to create & interact with a batchv1.Job

pkg/resources/deployment/deployment_test.go, pkg/resources/deployment/options.go
Unfortunately I missed in #462 to define the option to set the selector on a deployment besides the default one. This PR addresses it and adds the `WithSelectors` option to define the selector labels for a deployment.
=> Add option to set selector on deployment resource

README.md, pkg/environment/flags.go, pkg/environment/images.go, pkg/environment/images_test.go, pkg/environment/standard.go, pkg/environment/testdata/images.yaml, pkg/images/file/file.go, pkg/images/file/file_test.go, pkg/images/file/testdata/images.yaml
Downstream we build images before running the tests and we don't use `ko`, so a file-based image resolver helps us referencing images differently.
=> Add file-based image resolver

pkg/resources/deployment/deployment.go
- :bug: Set the image name in the deployment resources `Install`
/kind bug
=> Fix deployment resource image setting

pkg/eventshub/103-pod.yaml, pkg/eventshub/eventshub_test.go
When using eventshub on pods with istio sidecar injected, they terminate with failures since until the istio sidercar is ready network is not working so events will fail to get delivered to the configured destination.
=> Restart eventshub on failure

pkg/environment/interfaces.go, pkg/environment/magic.go, test/e2e/environment_test.go
The below pseudo-code will run `f1` and `f2` sequentially:
```
Environment.Test(ctx, t, f1)
Environment.Test(ctx, t, f2)
```
However, some features can be beneficial to run them in parallel
with other parallel features since most of our tests are waiting
for something to become ready.
This PR adds:
```
Environment.ParallelTest(ctx, t, f1)
Environment.ParallelTestSet(ctx, t, fs1)
```
to specify that a feature or a feature set can be run
in parallel.
- Allow specifying parallel tests for parallelizable features
/kind <kind>
Fixes #
```release-note
Allow specifying parallel tests for parallelizable features
```
=> Allow specifying parallel tests for parallelizable features

README.md, pkg/environment/flags.go, pkg/environment/magic.go, pkg/environment/namespace.go, pkg/environment/standard.go
For testing istio with eventing, I'd like to specify a specific
namespace so that it can be pre configured with some istio-specific
configurations.
=> Allow using a prespecified namespace for running tests

pkg/environment/images.go, pkg/feature/feature.go, pkg/resources/cronjob/cronjob.go, pkg/resources/cronjob/cronjob.yaml, pkg/resources/cronjob/cronjob_test.go, pkg/resources/cronjob/options.go, test/e2e/resources_test.go
SinkBinding tests use CronJobs, this will replace the `job` package in eventing
- Support cronjobs
=> Support cronjobs

pkg/resources/cronjob/cronjob.go, pkg/resources/cronjob/cronjob.yaml, pkg/resources/cronjob/cronjob_test.go
If the SinkBinding selection mode is set to inclusion, in eventing we need to set the `bindings.knative.dev/include: true` label on the Job to allow SinkBinding to make changes to the resulting Job.
=> Support setting Job labels for cron jobs

pkg/resources/cronjob/cronjob.yaml, pkg/resources/cronjob/cronjob_test.go
Labels like `foo: true` are invalid, so we need to quote them.
=> Quote label values for cronjob

pkg/resources/cronjob/cronjob.yaml, pkg/resources/cronjob/cronjob_test.go, pkg/resources/deployment/deployment.yaml, pkg/resources/deployment/deployment_test.go, pkg/resources/job/job.yaml, pkg/resources/job/job_test.go, pkg/resources/namespace/namespace.yaml, pkg/resources/namespace/namespace_test.go, pkg/resources/pod/pod.yaml, pkg/resources/pod/pod_test.go, pkg/resources/secret/secret.yaml, pkg/resources/secret/secret_test.go, pkg/resources/service/service.yaml, pkg/resources/service/service_test.go
Follow up on #503 to quote labels and selectors of all existing resources:
Labels like `foo: true` are invalid, so we need to quote them.
=> Quote label and selector values

cmd/eventshub/main.go, pkg/eventshub/102-service.yaml, pkg/eventshub/104-forwarder.yaml, pkg/eventshub/event_log.go, pkg/eventshub/eventshub_image.go, pkg/eventshub/eventshub_test.go, pkg/eventshub/forwarder/forwarder.go, pkg/eventshub/options.go, pkg/eventshub/resources.go, pkg/eventshub/sender/sender.go, pkg/eventshub/utils.go, pkg/resources/knativeservice/ksvc.go
- :gift:
- Add option for global environment to enable Knative Service Forwarder for EventsHub receiver:
```
ctx, env := global.Environment(eventshub.WithKnativeServiceForwarder)
```
- Implement forwarder that combines functionality from receiver and sender. It logs the events that are forwarded but doesn't record them (it doesn't send a k8s event for them).
- Tests which use EventsHub can stay untouched if they don't want to use the Knative Service forwarder. Tests which want to use it can re-use Features from other tests and only configure global environment like in the example below:
```
func TestPingSourceBrokerTriggerKsvc(t *testing.T) {
t.Parallel()
ctx, env := global.Environment(
knative.WithKnativeNamespace(system.Namespace()),
knative.WithLoggingConfig,
knative.WithTracingConfig, …
```
=> Knative Service forwarder for EventsHub

pkg/environment/magic.go, pkg/feature/feature.go
When calling env.Finish() the resources that have been created by such environment should be removed.
So far, we were relying on the namespace deletion to clean up resources, however, if a precreated namespace is used for multiple tests and multiple environments, the cluster is full of resources that are not needed anymore since those tests were successfully run.
=> Remove resources when terminating the environment

pkg/environment/execution.go, pkg/environment/magic.go, pkg/feature/feature.go, pkg/feature/timing.go, pkg/milestone/emitter_log.go, test/e2e/environment_test.go
Fixes https://github.com/knative/eventing/issues/6934
When testing TLS we are facing the challenge of defining tests which should be executed based on the feature flag value.
For example, when we will add tests for [1], we will need to execute the test only when the transport-encryption feature flag is set to one of permissive or strict.
[1] https://github.com/knative/eventing/issues/6932
The idea is to have an additional feature timing called `Prerequisite` and the usage would look like this:
```golang
f.Prerequisite("other timings should not run", func(ctx context.Context, t feature.T) (feature.PrerequisiteResult, error) {
// check feature flag value .. 
// ...
return feature.PrerequisiteResult{ShouldRun: false}, nil
})
f.Setup("failed setup", func(ctx context.Context, t feature.T) { …
```
=> Add support for feature-level prerequisites

.github/workflows/kind-e2e.yaml, pkg/environment/magic.go, pkg/eventshub/103-pod.yaml, pkg/eventshub/105-certificate-ca.yaml, pkg/eventshub/105-certificate-service.yaml, pkg/eventshub/105-issuer-ca.yaml, pkg/eventshub/105-issuer-certificate.yaml, pkg/eventshub/eventshub_test.go, pkg/eventshub/options.go, pkg/eventshub/receiver/receiver.go, pkg/eventshub/resources.go, pkg/eventshub/utils.go, pkg/feature/context.go, pkg/k8s/wait.go, pkg/manifest/installer.go, pkg/resources/secret/secret.go, pkg/resources/service/service.go, test/e2e-common.sh, test/e2e-tests.sh, test/e2e/eventshub/main_test.go, test/e2e/eventshub/receiver_readiness.go, test/e2e/eventshub/receiver_tls_test.go
This PR adds support to create a receiver with a TLS listener.
For test authors, to create a test with a TLS sink, it offers a few main
entry points:
- `eventshub.WithTLS` this is an `environment.EnvOpts`.
it provision a root CA for a given environment (namespace) and makes
CA certs for the root CA available in the environment's context
- `eventshub.StartReceiverTLS`, this is similar to
the existing `eventshub.StartReceiver` with the addition of
provisioning TLS key pair for the server based on the root CA
- `eventshub.GetCACerts` this is the method that can be used to retrieve
the CA certs provisioned using `eventshub.WithTLS` on the environment.
When `eventshub.StartReceiverTLS` is used as option on `eventshub.Install`,
the eventshub receiver will enforce that requests are submitted …
=> Support receiving events to HTTPS endpoints in eventshub

pkg/eventshub/event_info.go, pkg/eventshub/receiver/receiver.go
This change expands the TLS verification on the receiver to verify that we're not using "insecure ciphers".
In addition, for server side requests, requests.URL.Scheme doesn't contain the scheme used by the client (documentation confirms this)
=> Improve receiver TLS verification

pkg/eventshub/103-pod.yaml, pkg/eventshub/104-forwarder.yaml, pkg/eventshub/eventshub_test.go, pkg/eventshub/rbac/100-sa.yaml, pkg/eventshub/rbac/101-rbac.yaml, pkg/eventshub/rbac/rbac.go, pkg/eventshub/rbac/rbac_test.go, pkg/eventshub/resources.go
By having [1] and the fact that:
- eventshub's RBAC resources are namespace global
- multiple parallel tests might run in a single namespace
we end up removing resources that are in active use by other tests.
[1] https://github.com/knative-sandbox/reconciler-test/commit/8a5db1ba56ec02538eec7de545365eae9ea3ced7
=> eventshub RBAC resources independent to avoid deletion conflicts

resources/certificate/certificate.go, test/config/selfsigned-ca-issuer.yaml, test/config/selfsigned-issuer.yaml, test/config/test-tls-certificate.yaml, test/e2e-common.sh, test/e2e/resources_test.go
This PR adds a common StepFn for rotating a cert-manager certificates.
This PR in combination with https://github.com/knative-sandbox/reconciler-test/pull/548 will allow writing E2E cert-rotation tests that are generic for any implementation
Part of https://github.com/knative/eventing/issues/7039
=> Support rotating TLS certificates

pkg/eventshub/assert/step.go, pkg/eventshub/event_info.go, pkg/eventshub/event_info_store.go, pkg/eventshub/receiver/receiver.go, pkg/eventshub/sender/sender.go, test/e2e/eventshub/receiver_tls_test.go
For certificate rotation testing, we need to be able to match that the eventshub sender while sending requests received the "latest" / "rotated" peer certificate.
The use would look like this:
```golang
f.Assert("Sender received expected peer certificate", assert.OnStore(sourceName).
MatchPeerCertificatesReceived(assert.MatchPeerCertificatesFromSecret(secretName, "tls.crt")).
AtLeast(1),
)
```
- Support matching received peer certificates
- support defining matchers with context
Part of https://github.com/knative/eventing/issues/7039
=> Support matching sender received peer certificates for certs rotation testing

pkg/eventshub/sender/sender.go, test/e2e/eventshub/receiver_tls_test.go
For testing TLS certs rotation we need to force TLS handshakes multiple times
=> Create a client and transport per request in the TLS case to force TLS handshakes

pkg/eventshub/102-service.yaml
This helps with Istio testing since without name istio doesn't know the protocol 
- https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection
- https://istio.io/latest/docs/ops/common-problems/security-issues/#make-sure-you-are-not-using-http-only-fields-on-tcp-ports
=> [release-1.10] Add name to port

pkg/eventshub/103-pod.yaml, pkg/eventshub/eventshub_test.go, pkg/eventshub/rbac/100-sa.yaml, pkg/eventshub/rbac/101-rbac.yaml, pkg/eventshub/rbac/rbac.go, pkg/eventshub/rbac/rbac_test.go, pkg/eventshub/resources.go
Back-port of https://github.com/knative-extensions/reconciler-test/pull/538.
=> [RELEASE-1.10] eventshub RBAC resources independent to avoid deletion conflicts

pkg/eventshub/105-certificate-service.yaml, pkg/eventshub/resources.go
Currently the domain of the eventshub certificate dnsNames are hard coded to `cluster.local`.
This leads to a couple of TLS test failures when the tests are running in kind with a custom cluster domain (e.g. in case of the eventing e2e tests via GH actions).
This PR addresses it and uses the ClusterDomain from the cluster on which the test is running on.
=> Use cluster domain in eventshub certificates dnsNames

pkg/eventshub/forwarder/forwarder.go
The eventshub forwarder should forward headers such as Kn-Namespace.
The sending client automatically adds some headers such as User-Agent and Content-Length. We also don't want to forward tracing-related headers starting with X- and Traceparent. So this feature only forwards specific headers related to Knative.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Forward headers starting with Kn-

pkg/eventshub/forwarder/forwarder.go
This is a follow-up to https://github.com/knative-extensions/reconciler-test/pull/572 . This PR doesn't choose specific headers but forwards everything by re-using the original request and modifying it.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Use the Request in Forwarder directly

pkg/eventshub/eventshub_test.go, pkg/manifest/options.go
- Adds an annotation to the istio-proxy to hold the application start until the proxy is ready
- Verified on https://github.com/openshift-knative/serverless-operator/pull/2228
=> Add hold annotation for istio-proxy

pkg/environment/magic.go, pkg/environment/namespace.go
This option is useful when it's necessary to test stuff across multiple namespaces which require some pre-setup steps. (e.g. testing traffic isolation with Istio between namespaces)
The test namespace can be defined for environment like this:
```
global.Environment(
environment.WithNamespace(namespace),
...
environment.Managed(t),
)
```
This option takes precedence over the --environment.namespace flag.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Option to override namespace for magic environment

pkg/eventshub/eventshub.go, pkg/eventshub/istio_quit.go
- :lady_beetle: Call the quit when the eventshub is closed
/kind bug
Fixes #590
```release-note
The eventshub will call the Istio's /quitquitquit endpoint at exit
```
=> :lady_beetle: Call the Istio' quit when the eventshub is closed

.github/workflows/go-test-windows.yaml, .github/workflows/kind-e2e.yaml, go.mod
Update go version for tests to 1.20, as we had some issues in #564
```
Error: vendor/k8s.io/kube-openapi/pkg/cached/cache.go:242:16: undefined: atomic.Pointer
note: module requires Go 1.19
Error: vendor/go.uber.org/multierr/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
Error: vendor/k8s.io/client-go/tools/cache/synctrack/lazy.go:29:15: undefined: atomic.Pointer
note: module requires Go 1.20
```
=> Update to golang 1.20

pkg/eventshub/resources.go, pkg/manifest/manifest.go
Downstream I'm getting this `SINK` value due to
the fact that `sinkURL` is now an `Addressable`:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
name: sink-nwvhvrgz
namespace: test-fbszrpbn
spec:
template:
spec:
containers:
- env:
- name: NAME
value: sink-nwvhvrgz
- name: NAMESPACE
value: test-fbszrpbn
- name: SINK
value:
<nil> http://sink-nwvhvrgz-twzpetzr.test-fbszrpbn.svc.cluster.local <nil>: null
- name: EVENT_GENERATORS
value: forwarder
- name: EVENT_LOGS
value: logger
- name: K_CONFIG_LOGGING
value: '{"zap-logger-config":"{\n  \"level\": \"info\",\n  \"development\": false,\n  \"outputPaths\": [\"stdout\"],\n  \"errorOutputPaths\": [\"stderr\"],\n  \"encoding\": \"json\",\n  \"encoderConfig\": {\n    \"timeKey\": \"ts\",\n    \"levelKey\": \"level\",\n    \"nameKey\": …
```
=> Fix forwarder SINK URL

pkg/eventshub/options.go, pkg/eventshub/utils.go
Currently the user has to indicate via the eventhub option `OIDCValidToken` that a valid token should be added to the senders request.
This PR changes it to be the default behavior, if the sink has an audience set.
=> Enable OIDCAuth for eventshub sender when sink has an audience

.github/workflows/kind-e2e.yaml, pkg/eventshub/options.go, pkg/eventshub/rbac/101-rbac.yaml, pkg/eventshub/receiver/receiver.go, pkg/eventshub/utils.go, test/e2e-tests.sh, test/e2e/eventshub/oidc_test.go
Fixes https://github.com/knative/eventing/issues/7334
- :gift: Add OIDC support to eventshub receiver
As soon as an eventshub receiver was setup with an audience (via `OIDCReceiverAudience(aud)`), it will check verify the JWTs of incoming requests (and respond with a 401, if failed).
**Hints for reviewers:**
* Added the `OIDCSinkAudience(aud)` option too, to define the audience of the sink, which is helpful/needed, if the audience of the sink can't be determined by the source itself (e.g. when the sink does not provide the `.status.address.audience` field)
* We can add the OIDC service account name to the eventInfo and then later base some asserter on it, but I didn't see a real usecase for it at that time of the OIDC implementation
* We verify the tokens with the TokenReviewAPI to not …
=> Support OIDC in eventshub receiver

test/e2e/eventshub/oidc_test.go
Use `ParallelTest()` and `ParallelTestSet()` to speed up OIDC e2e tests.
Follow up on https://github.com/knative-extensions/reconciler-test/pull/612#discussion_r1363585112
=> Use ParallelTest*() for OIDC tests

pkg/eventshub/sender/sender.go
This will enable us to run tests with both OIDC and TLS enabled.
=> Configure sender with CA certs when provided

pkg/environment/timings.go, pkg/feature/feature.go, pkg/state/timings.go
- :broom: Use context poll interval/timeout in DeleteResources
/kind cleanup
Deleting resources with finalizer also requires reconciliation, so waiting for a resource to be deleted is in principle no different to waiting for it to become Ready. In some cases it makes sense to increase the timeouts for waiting for deleted resources. Therefore, we'll apply the same poll interval/timeouts for waiting for deletion as set in ContextWithPollTimings, instead of the original hardcoded values.
Also moves the ContextWithPollTimings and PollTimingsFromContext to `state` package to break dependency cycle
```release-note
feature.DeleteResources now uses poll interval/timeouts from Context for waiting for the resources to be deleted, instead of the original hardcoded values
```
=> use context poll interval/timeout in DeleteResources

pkg/environment/standard.go
- Add new function which creates a standard global environment using the provided rest config rather than parsing a new config.
This is needed for https://github.com/knative/eventing/pull/7626
=> Create standard global environment with provided rest config

pkg/eventshub/assert/step.go
- :broom: make MatchPeerCertificatesFromSecret work with certificate chains
When using intermediate CAs, the secret can contain more than one certificate (a certificate chain), so the comparison
```
for _, cert := range info.Connection.TLS.PemPeerCertificates {
if cert == string(value) 
```
cannot work
Instead, we parse all the  certificates in the chain from the secret with `pem.Decode` , and we make sure that each of the certificates is present in the `info.Connection.TLS.PemPeerCertificates`
=> make MatchPeerCertificatesFromSecret work with certificate chains

.github/workflows/knative-downstream.yaml
=> Remove deprecated repos from downstream tests

pkg/eventshub/forwarder/forwarder.go
Currently we have issues in the forwarder as the request body is read twice (one time to get the message/cloudevent and a second time when the request/clone is sent again (`o.httpClient.Do(req)`)).
This PR addresses it and makes sure the request which is send from the forwarder has the received event in its body.
Hint: I was also checking to clone the request earlier, but `Request.Clone()` seems not really clone the body (https://github.com/golang/go/blob/33013e8ea821629858643f24c55805f5ddf316b5/src/net/http/request.go#L383)
=> Forwarder: Write received event to request

pkg/eventshub/forwarder/forwarder.go
- :broom: eventshub forwarder, don't clone the Host header of the original request
=> eventshub forwarder, don't clone Host header

.github/workflows/kind-e2e.yaml
- Upgrade the go version in KinD tests
=> fix: KinD tests now use go 1.21.x

pkg/images/ko/publish.go
It's been reported here as a bug https://github.com/knative/eventing/pull/7799#issuecomment-2025228385
=> Bump default Ko version

pkg/eventshub/assert/event_info_matchers.go, pkg/eventshub/event_info.go, pkg/eventshub/receiver/receiver.go
Add a event matcher, to check the OIDC user name of the received event.
This adds two new functions:
* `MatchOIDCUser(username)` to directly check if the given username matches the OIDC username in EventInfo
* `MatchOIDCUserFromResource(gvr, resourceName)` to check, if the OIDC username from the given resource matches the OIDC username in the EventInfo
This allows e.g. testcases like the following:
```
...
f.Alpha("Broker").
Must("subscriber receives event from correct sender identity", eventassert.OnStore(sink).MatchWithContext(eventassert.MatchOIDCUserFromResource(triggerresources.GVR(), triggerName)).Exact(1))
```
=> Add matcher for used OIDC user name

pkg/eventshub/forwarder/forwarder.go
Currently, the forwarder is duplicating headers the tests fail when testing components within an Istio mesh.
=> Fix forwarder body buffering

go.mod, go.sum, pkg/eventshub/assert/event_info_matchers.go, vendor/knative.dev/pkg/apis/duck/v1/auth_types.go, vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go, vendor/modules.txt
Update the OIDC user matcher to work with .authStatus.serviceAccountName**s** (plural form - https://github.com/knative/pkg/pull/3032)
=> Update OIDC user matcher to work with `.authStatus.serviceAccountNames`

pkg/environment/standard.go, pkg/environment/timings.go
The test client used by every running test and we've seen many instances where we get rate-limited for no reason.
=> Increase default QPS and Burst to avoid getting rate limited

pkg/environment/magic.go, pkg/feature/feature.go, test/e2e/environment_test.go
This is a feature that might allow simplifying setting up tests to prevent starvation, for example, this one https://github.com/knative/eventing/pull/7911 while continuing to get the benefits of the parallel phases and avoiding having the error prone calls like `eventshub.Install(subscriberName2, eventshub.StartReceiver)(ctx, t)`
```golang
f.Group("install subscribers", func(f *Feature) {
f.Setup("install eventshub", eventshub.Install(subscriberName1, eventshub.StartReceiver))
})
f.Group("install brokers", func(f *Feature) {
f.Setup("install broker1", broker.Install(...))
f.Setup("install broker2", broker.Install(...))
})
f.Group("ready brokers", func(f *Feature) {
f.Requirement("ready broker1", broker.IsReady(...))
f.Requirement("ready broker2", broker.IsReady(...))
f.Assert("addressable …
```
=> Introduce phase groups for features

pkg/eventshub/forwarder/forwarder.go
=> Fix `nil` pointer error in forwarder from file

pkg/eventshub/options.go, pkg/eventshub/receiver/receiver.go
This is needed to test changes like https://github.com/knative/eventing/pull/8151
- Add options for verifying the event format in the eventshub receiver
- Add code to the receiver to verify the event format when the right env var is set
<!--
In addition, categorize the changes you're making using the "/kind" Prow command, example:
=> feat: add support for verifying the event format in the eventshub receiver

pkg/eventshub/options.go, pkg/eventshub/resources.go, pkg/eventshub/utils.go
Adds an option to set the OIDC identity to use for the eventshub sender
=> Allow to configure OIDC subject name for eventshub sender

pkg/manifest/options.go, pkg/resources/cronjob/cronjob_test.go, pkg/resources/deployment/deployment_test.go, pkg/resources/deployment/options.go, pkg/resources/job/options.go
As per title.
Seen in https://github.com/knative-extensions/eventing-istio/pull/519, that `WithIstioPodLabels()` overrides existing labels completely (e.g. on Cronjobs).
This PR addresses it and appends the labels instead
=> Fix WithLabels and WithPodLabels to append to eventually existing labels

pkg/manifest/manifest.go
Seeing https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4461/reconciler-tests-namespaced-broker_eventing-kafka-broker_main/1948812764961050624 
>  trigger.go:213: failed to update resource Operation cannot be fulfilled on triggers.eventing.knative.dev "trigger-fionpyxa": the object has been modified; please apply your changes to the latest version and try again - Resource:
Not many tests re-create a resource with the same name, TestBrokerDeletedRecreated re-creates a Trigger, so it sometimes hits an "object is modified" error on update.
- :broom: Retry update conflicts in manifest Apply
=> retry update conflicts in manifest Apply
