knative-extensions/reconciler-test

- pkg/test/environment/cluster.go
Should enable - https://github.com/knative/networking/pull/212
/assign @vaikas @n3wscott
> support configuring cluster domains

- pkg/eventshub/options.go
- pkg/test_images/eventshub/sender/sender.go
Fix #43
- :gift: Expose all the features of eventshub event sender
> Expose all the parameters of the event sender in eventshub

- pkg/eventshub/100-sa.yaml
- pkg/eventshub/101-rbac.yaml
- pkg/eventshub/102-service.yaml
- pkg/eventshub/103-pod.yaml
- pkg/eventshub/eventshub_test.go
- pkg/eventshub/resources.go
- pkg/manifest/templates.go
- test/example/config/echo/echo_test.go
- Enable `Example` type tests for local yaml templates.
Fixes https://github.com/knative-sandbox/reconciler-test/issues/54
```release-note
NONE
```
> Enable `Example` type tests for local yaml templates.

- pkg/eventshub/eventshub_test.go
- pkg/manifest/templates.go
- Sort the filenames for yaml output. Tests fail sometimes based on order of files in a map.
/kind cleanup
Fixes #
```release-note
NONE
```
> Sort the filenames for yaml output

- pkg/k8s/steps.go
- pkg/k8s/wait.go
- test/example/recorder_feature.go
- :gift: Adding `k8s.IsAddressable()` to test if the Addressable duck type has a non-nill address.
- :broom: Adding more logic to `k8s.IsReady()` to help test batch and non-standard resources.
Fixes #58 
```release-note
- :gift: Adding `k8s.IsAddressable()` to test if the Addressable duck type has a non-nill address.
- :broom: Adding more logic to `k8s.IsReady()` to help test batch and non-standard resources.
```
> add isAddressable, improve isReady

- pkg/eventshub/resources.go
- Just a little doc on the expectations of eventshub.Install
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> eventshub.Install docs

- go.mod
- go.sum
- vendor/modules.txt
Following https://github.com/knative/pkg/blob/master/RELEASE-LEADS.md#manuallocal-release-branch-creation, these changes show up.
> Update to fix releasability

- pkg/eventshub/event_info_matchers.go
- pkg/eventshub/event_info_store.go
- pkg/eventshub/step.go
- test/example/recorder_feature.go
Fix #42
- :gift: DSL to perform assertions on eventshub store. This DSL is a beginning, we might extend in future to have other assertions on the event store
> DSL to perform assertions on eventshub store

- pkg/eventshub/assert/event_info_matchers.go
> Re-exporting EventInfo

- OWNERS_ALIASES
> Added myself between wg-leads

- OWNERS_ALIASES
> Update owner aliases with modern data

- pkg/images/cmd.go
- pkg/knative/logging_config.go
- :bug: Now image building prints ko stderr to stdout
- :bug: Fixed a nit in a config-logging error
> Some fixes to improve error logging

- pkg/feature/feature.go
- pkg/feature/feature_test.go
- :gift: Added method `NewFeature` to automatically assign the feature name from the caller name
> Automatic feature name

- pkg/eventshub/options.go
- pkg/test_images/eventshub/receiver/receiver.go
- :gift: Add response wait time in order to "slow down" the dispatch of events
> [eventshub] Add response wait time

- .github/workflows/kind-e2e.yaml
- .github/workflows/knative-downstream.yaml
Also update ko and reorganize a bit the kind-e2e yaml
> Fix Github actions

- pkg/environment/magic.go
- Introduce InNamespace option so that you can run tests against existing namespaces. Basic idea being that if I want to decouple creation of resources in a namespace that the tests run against, this will allow me to create a namespace, resources under test and then execute the tests against that namespace.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> add InNamespace option for pre-existing namespace tests

- pkg/manifest/installer.go
Add ability to parse files that are non-local to the .go file that consumes them. Meant to be able to be used to test different brokers against the conformance tests.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> add variant of install from other places

- pkg/environment/timings.go
fixes https://github.com/knative-sandbox/reconciler-test/issues/137
> fix some pasta on PollTimingsFromContext

- pkg/k8s/wait.go
fixes https://github.com/knative-sandbox/reconciler-test/issues/135
> fix issue where conditions are empty

- pkg/test_images/eventshub/event_info.go
- pkg/test_images/eventshub/sender/sender.go
Fix #148, which introduced a panic when sending non-events
> [eventshub] Fix #148

- pkg/test_images/eventshub/event_info.go
- pkg/test_images/eventshub/sender/sender.go
- Print all the headers (including ce-* headers) so that it's easier to see what was actually sent.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> print all the headers, including ce-*

- pkg/test_images/eventshub/sender/sender.go
I want to be able to configure the sender to use an input yaml file, but I need to stage a bit of a refactor to get the logic seperated a little. 1/2
> [EventsHub] Refactor sender to use a generator

- pkg/k8s/wait.go
dump the logs off pods that fail to start.
> add debug to failed start pods

- pkg/environment/magic.go
- pkg/feature/context.go
- pkg/feature/feature.go
- pkg/manifest/installer.go
- :gift: Make Feature part of the Context. We've seen some Features create many resources and for longer running tests, there's really no reason to keep the resources around until the environment finishes. This has additional uses, but this was the first pressing one.
- Thoughts??
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> add feature to context, add refs to feature

- README.md
Trying to add notes about how and why to use State.
> document Store and KVStore

- pkg/feature/feature.go
- test/example/echo_feature.go
> Delete feature resources

- pkg/manifest/templates.go
Need to still figure out how to make this work with the FS apis, but that is a problem for another day.
> Fix ExecuteTemplates/ExecuteYAML to work with single files again

- pkg/eventshub/prober.go
- pkg/eventshub/resources.go
Cherry-pick (actually just merge) #218 into release 0.24
/assign @matzew
> Fix eventshub race (#218)

- pkg/eventshub/options.go
- pkg/eventshub/prober.go
- pkg/eventshub/receiver/receiver.go
- test/example/prober_feature.go
- :gift: Add a new Option(DropEventsResponseCode) for eventshub to specify the HTTP response code
when events should be dropped
/kind <kind>
Fixes https://github.com/knative-sandbox/reconciler-test/issues/211
```release-note
```
**Docs**
```docs
```
> Add DropEventsResponseCode for eventshub

- pkg/eventshub/options.go
- pkg/eventshub/sender/sender.go
- :gift: DELAY and PERIOD now supports Golang duration format. If the last unit is not specified, add 's' to the duration string.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Sender now support sub-second period and delay

- go.mod
- go.sum
- vendor/knative.dev/hack/release.sh
- vendor/modules.txt
> Backport deps to release-1.0

- pkg/k8s/job.go
- pkg/k8s/steps.go
- pkg/k8s/wait.go
- test/example/echo_feature.go
Test logged using `log.P*` are not straightforward to find for debugging issues
so, I'm passing `feature.T` to `Wait*` functions.
- Test scoped logs in wait functions
/kind bug
Fixes #
```release-note
Add feature.T parameter to Wait* functions for test-scoped logging.
```
**Docs**
```docs
```
> Test scoped logs in wait functions

- pkg/environment/interfaces.go
- pkg/environment/magic.go
- pkg/milestone/emitter_composite.go
- pkg/milestone/emitter_log.go
- pkg/milestone/factory.go
As of now, it's hard to debug failed E2E tests without detailed
logging.
This patch adds a new `logEmitter` which is composed and used
with the already present `NilSafeClient` emitter.
The `logEmitter` logs events using the managed `T`
instance, if configured.
- Add log milestone emitter
```release-note
Add log milestone emitter
```
**Docs**
```docs
None
```
> Add log milestone emitter

- pkg/feature/feature.go
Foreground propagation has a better consistency model
to deal with especially for tests where we want to delete
a resource and then recreate it.
- Use foreground propagation when deleting resources
```release-note
Use foreground propagation when deleting resources
```
**Docs**
```docs
None
```
> Use foreground propagation when deleting resources

- pkg/eventshub/prober.go
> added assertReceivedNone function to reconciler-test prober

- pkg/environment/magic.go
- pkg/feature/feature.go
- pkg/feature/feature_test.go
- pkg/feature/level.go
- pkg/feature/states.go
- pkg/feature/timing.go
- pkg/state/kvstore.go
This would help debug test failures.
> Improve logging for features and their state

- pkg/k8s/wait.go
This would help debug failed tests.
> Log pod state while waiting for pod to be ready

- pkg/milestone/emitter_log.go
There is noise in the logs of the emitter because we were
logging `feature.T`:
```
&{{{{0 0} 0 0 0 0} [32 32 32 32 45 45 45 32 80 65 83 83 58 32 84 101 115 116 66 114 111 107 101 114 67 111 110 102 111 114 109 97 110 99 101 47 80 114 101 114 101 113 117 105 115 105 116 101 32 40 50 53 46 48 51 115 41 10 32 32 32 32 32 32 32 32 45 45 45 32 80 65 83 83 58 32 84 101 115 116 66 114 111 107 101 114 67 111 110 102 111 114 109 97 110 99 101 47 80 114 101 114 101 113 117 105 115 105 116 101 47 47 83 101 116 117 112 47 105 110 115 116 97 108 108 95 114 97 98 98 105 116 109 113 99 108 117 115 116 101 114 95 34 114 97 98 98 105 116 98 114 111 107 101 114 34 32 40 48 46 48 50 115 41 10 32 32 32 32 32 32 32 32 45 45 45 32 80 65 83 83 58 32 84 101 115 116 66 114 111 107 101 114 67 111 110 102 111 114 …
```
> Remove log emitter noise

- pkg/manifest/installer.go
In eventing, we're getting a lot of these errors.
Tried in https://github.com/knative/eventing/pull/6176 and it removes
a bunch of flaky tests.
> Retry on context deadline exceeded errors

- pkg/eventshub/receiver/receiver.go
This is needed for testing https://github.com/knative-sandbox/eventing-kafka-broker/pull/2374
- Allow defining a custom response body for skipped events
> [eventshub] Allow defining a custom response body for skipped events

- pkg/eventshub/options.go
Related to https://github.com/knative-sandbox/reconciler-test/commit/cd61a92720167518e9f1a3b3d273037815ecd63f
Add a helper function to define an additional env variable.
> Add DropEventsResponseBody EventsHubOption

- pkg/environment/magic.go
- pkg/manifest/installer.go
- :wastebasket: Removal of deprecated, unused functions.
/kind cleanup
Follow up on #294
> :wastebasket: Removal of deprecated, unused functions.

- .github/workflows/go-test-windows.yaml
- .github/workflows/knative-downstream.yaml
- Remove discovery from downstream tests
- Update windows action to go 1.18
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Cleanup github action

- go.mod
- go.sum
- pkg/eventshub/103-pod.yaml
- pkg/eventshub/resources.go
- pkg/k8s/pod.go
- pkg/manifest/options.go
- vendor/knative.dev/pkg/test/security/security.go
- vendor/modules.txt
Related to https://github.com/knative/eventing/issues/6563
This is to allow running test pods in namespace with enforced "restricted" pod security standard.
This PR builds on https://github.com/knative/pkg/pull/2625.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Define SecurityContext for test Pods

- pkg/environment/magic.go
- 🎁  Resources can be created in namespaces other than the test namespace
> Adds ability for resources to override namespace in template config.

- pkg/environment/logging.go
- pkg/environment/magic.go
- pkg/feature/feature.go
- pkg/feature/feature_test.go
> Protect references collection with mutex for concurrent access

- pkg/resources/secret/options.go
- pkg/resources/secret/secret.go
- pkg/resources/secret/secret.yaml
- pkg/resources/secret/secret_test.go
- :gift: Add helpers to create a Secret
Similar to #452 
> Add helpers to create & interact with a Secret

- pkg/resources/deployment/deployment.go
- pkg/resources/deployment/deployment.yaml
- pkg/resources/deployment/deployment_test.go
- pkg/resources/deployment/options.go
- :gift: Add helpers for a deployment resource
Similar to #452
> Add Deployment resource

- pkg/resources/namespace/namespace.go
- pkg/resources/namespace/namespace.yaml
- pkg/resources/namespace/namespace_test.go
- :gift: Add helpers for a namespace resource (from https://github.com/knative/eventing/tree/main/test/rekt/resources/namespace)
Similar to #452
> Add Namespace resource

- README.md
- pkg/environment/flags.go
- pkg/environment/images.go
- pkg/environment/images_test.go
- pkg/environment/standard.go
- pkg/environment/testdata/images.yaml
- pkg/images/file/file.go
- pkg/images/file/file_test.go
- pkg/images/file/testdata/images.yaml
Cherry-pick of https://github.com/knative-sandbox/reconciler-test/commit/f63559d4e680da44d553a424a745eb166b3067e6
> [release-1.7] Add file-based image resolver (#465)

- README.md
- pkg/environment/istio.go
- pkg/environment/istio_test.go
- pkg/environment/namespace.go
- pkg/environment/standard.go
- pkg/eventshub/103-pod.yaml
- pkg/eventshub/eventshub_test.go
- pkg/eventshub/resources.go
- pkg/manifest/options.go
- pkg/resources/deployment/deployment.go
- pkg/resources/deployment/options.go
- pkg/resources/job/job.go
- pkg/resources/job/options.go
- pkg/resources/pod/pod.go
This will allow start testing eventing-istio by using the existing
eventing test suite.
> Allow testing with istio enabled

- README.md
- pkg/environment/istio.go
- pkg/environment/istio_test.go
- pkg/environment/namespace.go
- pkg/environment/standard.go
- pkg/eventshub/103-pod.yaml
- pkg/eventshub/eventshub_test.go
- pkg/eventshub/resources.go
- pkg/manifest/options.go
Cherry-pick of https://github.com/knative-sandbox/reconciler-test/commit/e906aa6feb65802ac9bfe624f438ca32415764a4
> [release-1.9] Allow testing with istio enabled (#466)

- pkg/k8s/wait.go
The WaitForServiceReady was deploying a job without using the job package which means that the pod created out of the job is not annotated with istio injection annotation.
In addition, jobs with istio need to quit their sidecar when they ends so that the job can be considered "successful".
> Allow verify service readiness when istio is installed

- pkg/resources/service/service.go
As per title, minor improvement
> Set port name to service

- pkg/resources/service/service.go
> Move service port defaulting to config defaults

- .github/workflows/knative-downstream.yaml
This should fix the downstream test jobs
> Update downstream test Go version and remove eventing-natss

- pkg/eventshub/forwarder/forwarder.go
- The incoming Message has the data exhausted when we're forwarding so we create a new Message from the Event.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Eventshub forwarders properly forwards body/data

- pkg/eventshub/assert/step.go
As per title
/assign @pierDipi
> Fix eventshub MatchRejectedEvent assert method

- pkg/eventshub/103-pod.yaml
- pkg/eventshub/eventshub_test.go
- pkg/eventshub/options.go
- pkg/eventshub/receiver/receiver.go
- pkg/eventshub/resources.go
- pkg/eventshub/utils.go
- test/e2e/eventshub/receiver_tls_test.go
E2E test for sender TLS support https://github.com/knative-sandbox/reconciler-test/commit/4c1226f10ebf60a7f2e3c686b0c32f446cdb791b
> E2E test for sender TLS support

- pkg/milestone/emitter_tracing.go
- Remove deprecated usage after upgrade to latest dependency of knative.dev/pkg
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Remove deprecated usage of ZipkinTracingEnabled

- pkg/eventshub/eventshub_test.go
> [release-1.10] Fix unit tests

- cmd/eventshub/main.go
- pkg/eventshub/102-service.yaml
- pkg/eventshub/104-forwarder.yaml
- pkg/eventshub/event_log.go
- pkg/eventshub/eventshub_image.go
- pkg/eventshub/eventshub_test.go
- pkg/eventshub/forwarder/forwarder.go
- pkg/eventshub/options.go
- pkg/eventshub/resources.go
- pkg/eventshub/sender/sender.go
- pkg/eventshub/utils.go
- pkg/resources/knativeservice/ksvc.go
Backport of https://github.com/knative-extensions/reconciler-test/pull/517
> [release-1.10] Knative Service forwarder for EventsHub (#517)

- pkg/eventshub/104-forwarder.yaml
- pkg/eventshub/eventshub_test.go
- Add missing change from https://github.com/knative-extensions/reconciler-test/pull/565
> [RELEASE-1.10] Fix missing change in back-port #565

- pkg/eventshub/forwarder/forwarder.go
- cherry-pick from commit fa87766f8d898b147d5f2052b94326a53ece75f0 
/assign @mgencur
> Back-port fa87766f to release-1.10

- pkg/eventshub/resources.go
> Use base64URL en-/decoder from std lib

- pkg/feature/feature.go
- pkg/feature/logging.go
- Log the resource
- Log the events associated with such resource
> Improve logging message when deleting resources

- pkg/environment/flags.go
- pkg/environment/magic.go
- pkg/feature/feature.go
- pkg/state/timings.go
Backports two commits from main branch:
- use context poll interval/timeout in DeleteResources
- Flags for setting poll timeout and poll interval
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> [release-1.11] Flags for setting poll timeout and poll interval

- README.md
- hack/update-cert-manager.sh
- hack/update-codegen.sh
- hack/verify-codegen.sh
- pkg/environment/namespace.go
- pkg/eventshub/105-certificate-service.yaml
- pkg/eventshub/options.go
- pkg/eventshub/resources.go
- pkg/eventshub/utils.go
- pkg/resources/secret/secret.go
- test/e2e-common.sh
- test/install.sh
- third_party/cert-manager/00-namespace.yaml
- third_party/cert-manager/01-cert-manager.yaml
- third_party/cert-manager/02-trust-manager.yaml
This will allow testing cert-manager trust-bundle integration in Eventing https://github.com/knative/eventing/pull/7532
> Allow testing trust-bundle integration

- pkg/resources/deployment/deployment.yaml
- pkg/resources/deployment/deployment_test.go
- pkg/resources/deployment/options.go
This is for testing trust-manager integration in Eventing
> Support Deployment ConfigMap volumes

- README.md
- hack/update-cert-manager.sh
- hack/update-codegen.sh
- hack/verify-codegen.sh
- pkg/environment/namespace.go
- pkg/eventshub/105-certificate-service.yaml
- pkg/eventshub/options.go
- pkg/eventshub/resources.go
- pkg/eventshub/utils.go
- pkg/resources/secret/secret.go
- test/e2e-common.sh
- test/install.sh
- third_party/cert-manager/00-namespace.yaml
- third_party/cert-manager/01-cert-manager.yaml
- third_party/cert-manager/02-trust-manager.yaml
cherry-pick of https://github.com/knative-extensions/reconciler-test/pull/645
> [release-1.11] Allow testing trust-bundle integration (#645)

- hack/update-cert-manager.sh
- third_party/cert-manager/00-namespace.yaml
Similar to https://github.com/knative/eventing/pull/7572
> Remove kubectl dependency in hack/update-cert-manager.sh

- .github/workflows/go-test-windows.yaml
- .github/workflows/knative-downstream.yaml
- go.mod
- go.sum
> Update Golang to 1.21

- pkg/eventshub/104-forwarder.yaml
- :bug: Fix eventshub forwarder template "podannotations" placement
/kind bug
> fix eventshub forwarder pod template annotations

- pkg/environment/namespace.go
- test/e2e/environment_test.go
When testing SinkBinding, we need to make sure to include the label `bindings.knative.dev/include: true` so that the test works in both `inclusion` and `exclusion` selection mode.
https://knative.dev/docs/eventing/custom-event-source/sinkbinding/create-a-sinkbinding/#optional-choose-sinkbinding-namespace-selection-behavior
> Allow adding labels to environment namespace

- pkg/eventshub/options.go
- pkg/k8s/steps.go
- Add a new k8s NamespacedAddress function to return an address in a different namespace than env
- Add some eventshub options to send to resources in other namespaces
```release-note
Eventshub senders can deliver to resources in other namespaces
```
> feat: eventshub sender can send to resources in other namespaces

- pkg/eventshub/forwarder/forwarder.go
This allows testing `JobSink` https://github.com/knative/eventing/issues/7732
> Allow forwarder to forward events from files

- .github/workflows/go-test-windows.yaml
- .github/workflows/kind-e2e.yaml
- .github/workflows/knative-downstream.yaml
> Use `knative/actions/setup-go` to be in sync with other projects

- pkg/resources/secret/secret.go
> Actually use provided namesapce in `secret.IsPresentInNamespace`

- pkg/eventshub/103-pod.yaml
- pkg/eventshub/104-forwarder.yaml
- pkg/eventshub/eventshub_test.go
- pkg/eventshub/resources.go
- pkg/manifest/options.go
- pkg/resources/cronjob/cronjob.go
- pkg/resources/deployment/deployment.go
- pkg/resources/deployment/deployment.yaml
- pkg/resources/job/job.go
- pkg/resources/pod/pod.go
- pkg/resources/pod/pod_test.go
Ref: https://github.com/knative/eventing/issues/8204
> Use istio inject label

- pkg/feature/feature.go
- :broom: Retry failed deletions in DeleteResources
/kind cleanup
Related to https://github.com/knative-extensions/eventing-kafka-broker/issues/4455 , 
fixing errors like
```
feature.go:227: Warning, failed to delete test-sooyarik/kafka-source-utxqblxg of GVR: sources.knative.dev/v1, Resource=kafkasources: conversion webhook for sources.knative.dev/v1beta1, Kind=KafkaSource failed: Post "[https://kafka-webhook-eventing.knative-eventing.svc:443/resource-conversion?timeout=30s](https://kafka-webhook-eventing.knative-eventing.svc/resource-conversion?timeout=30s)": EOF
```
Retry the resource deletion if the delete returned an error. Trying to keep the rest of the logic intact. (we still want to only do one successful deletion)
> retry failed deletions in DeleteResources
